---
garage_version: "2.0.0"
garage_arch: x86_64-unknown-linux-musl
garage_download_url: "https://garagehq.deuxfleurs.fr/_releases/v{{ garage_version }}/{{ garage_arch }}/garage"

garage_user: garage
garage_group: garage

garage_meta_dir: /var/lib/garage/meta
garage_data_dir: /var/lib/garage/data

garage_s3_bind: "127.0.0.1:3900"
garage_rpc_bind: "127.0.0.1:3901"
garage_admin_bind: "127.0.0.1:3903"

garage_replication_factor: 1
garage_zone: local
garage_capacity: "1TB"

garage_bucket: depth-auth-dvc
garage_key_name: dvc-client
