apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Welcome</title></head>
    <body><h1>Welcome to Nginx!</h1>
    <p>This is a sample Nginx server running in Kubernetes.</p>
    </html>
