apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # Longhornが作成したStorageClassを指定
  resources:
    requests:
      storage: 1Gi
