apiVersion: v1
kind: ResourceQuota
metadata:
  name: chem-archive-quota
  namespace: chem-archive
spec:
  hard:
    pods: "10"
    persistentvolumeclaims: "1"
    requests.storage: "10Gi"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: chem-archive-container-limits
  namespace: chem-archive
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
      max:
        cpu: "2"
        memory: 2Gi
