apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: chem-archive
spec:
  provider:
    vault:
      server: "http://vault-vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "chem-archive-role"
          serviceAccountRef:
            name: "chem-archive-sa"
