apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chem-archive-tunnel
  namespace: chem-archive
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: chem-archive-tunnel
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: chem-archive
        property: cloudflared-token
