apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  targetNamespace: vault
  interval: 10m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      dev:
        enabled: false
      ha:
        enabled: false
      dataStorage:
        enabled: true
        size: 3Gi
    injector:
      enabled: false
    ui:
      enabled: false
