all:
  children:
    k8s-master:
      hosts:
        k8s-master:
          ansible_host:  "{{ lookup('env','TF_VAR_master_ip') }}"
          ansible_user: debian
          ansible_ssh_private_key_file: "{{ lookup('env','SSH_PRIVATE_KEY_PATH') }}"

    k8s-workers:
      vars:
        ansible_user: debian
        ansible_ssh_private_key_file: "{{ lookup('env','SSH_PRIVATE_KEY_PATH') }}"
      hosts: "{{ lookup('env','TF_VAR_worker_ips') | from_json }}"
