k8s-master:
  hosts:
    k8s-master:
      ansible_host:  "{{ lookup('env','TF_VAR_master_ip') }}"
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_k8s

k8s-workers:
  hosts:
    k8s-workers-1:
      ansible_host:  "{{ (lookup('env','TF_VAR_worker_ips') | from_json)[0] }}"
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_k8s
    k8s-workers-2:
      ansible_host:  "{{ (lookup('env','TF_VAR_worker_ips') | from_json)[1] }}"
      ansible_user: debian
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519_k8s
