apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: release-bot-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore  
  target:
    name: release-bot-secrets
    creationPolicy: Owner

  data:
    # DISCORD_TOKEN
  - secretKey: discord-token
    remoteRef:
      key: release-bot-secrets
      property: discord-token

    # GITHUB_TOKEN
  - secretKey: github-token-workflow
    remoteRef:
      key: release-bot-secrets
      property: github-workflow-token

    # GITHUB_OWNER
  - secretKey: github-owner
    remoteRef:
      key: release-bot-secrets
      property: github-owner

    # GITHUB_REPO
  - secretKey: github-repo
    remoteRef:
      key: release-bot-secrets
      property: github-repo

    # WORKFLOW_FILE
  - secretKey: workflow-file
    remoteRef:
      key: release-bot-secrets
      property: workflow-file
