apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps2bot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps2bot
  template:
    metadata:
      labels:
        app: ps2bot
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret-ps2bot
      containers:
      - name: ps2bot
        image: ghcr.io/seigo2016/ps2bot:latest@sha256:e695c1414577bc46eb61fb0e9ef6b0f03cf699a475117dfadb55283c67b11b79 # {"$imagepolicy": "flux-system:ps2bot"}
        env:
        - name: token
          valueFrom:
            secretKeyRef:
              name: ps2bot-secrets
              key: discord-token
