apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps2bot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps2bot
  template:
    metadata:
      labels:
        app: ps2bot
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret-ps2bot
      containers:
      - name: ps2bot
        image: ghcr.io/seigo2016/ps2bot:latest@sha256:306b8a0df1bdb153bf2a06364bcd86b5faf8e377180691090d74f09e39cd28d7 # {"$imagepolicy": "flux-system:ps2bot"}
        env:
        - name: token
          valueFrom:
            secretKeyRef:
              name: ps2bot-secrets
              key: discord-token
