apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps2bot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps2bot
  template:
    metadata:
      labels:
        app: ps2bot
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret-ps2bot
      containers:
      - name: ps2bot
        image: ghcr.io/seigo2016/ps2bot:latest@sha256:639ba1d883c563426705dd2de5bceada7e9ec7b56e5ae6a79a8d3a689b115808 # {"$imagepolicy": "flux-system:ps2bot"}
        env:
        - name: token
          valueFrom:
            secretKeyRef:
              name: ps2bot-secrets
              key: discord-token
