apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-registry-secret-ps2bot
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: ghcr-registry-secret-ps2bot
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .github_username }}",
                "password": "{{ .github_token }}",
                "auth": "{{ printf "%s:%s" .github_username .github_token | b64enc }}"
              }
            }
          }
  data:
  - secretKey: github_username
    remoteRef:
      key: ps2bot
      property: github-username
  - secretKey: github_token
    remoteRef:
      key: ps2bot
      property: github-token

