apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ps2bot-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: ps2bot-secrets
    creationPolicy: Owner
  data:
  - secretKey: discord-token
    remoteRef:
      key: ps2bot
      property: discord-token
