apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-backup
  namespace: atuin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi