apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-policy.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - secret-store.yaml
  - tunnel-external-secret.yaml
  - cloudflared-deployment.yaml
  - backup-pvc.yaml
