apiVersion: kustomize.config.k8s.io/v1beta1
kind: ResourcePolicy
metadata:
  name: keep-atuin-data
policy:
  keep:
    - kustomize.toolkit.fluxcd.io/v1/ExternalSecret
    - v1/PersistentVolumeClaim
    - v1/Secret
    - v1/ConfigMap
