apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-tunnel
  namespace: atuin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: atuin-tunnel
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: atuin
        property: cloudflared-token